config/routes.rb
ATest::Application.routes.draw do
  resources :offenders

end

app/models/offender.rb
class Offender < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offenders_controller.rb
class OffendersController < ApplicationController
  before_action :set_offender, only: [:show, :edit, :update, :destroy]

  # GET /offenders
  # GET /offenders.json
  def index
    @offenders = Offender.all
  end

  # GET /offenders/1
  # GET /offenders/1.json
  def show
  end

  # GET /offenders/new
  def new
    @offender = Offender.new
  end

  # GET /offenders/1/edit
  def edit
  end

  # POST /offenders
  # POST /offenders.json
  def create
    @offender = Offender.new(offender_params)

    respond_to do |format|
      if @offender.save
        format.html { redirect_to @offender, notice: 'Offender was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offender }
      else
        format.html { render action: 'new' }
        format.json { render json: @offender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offenders/1
  # PATCH/PUT /offenders/1.json
  def update
    respond_to do |format|
      if @offender.update(offender_params)
        format.html { redirect_to @offender, notice: 'Offender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offenders/1
  # DELETE /offenders/1.json
  def destroy
    @offender.destroy
    respond_to do |format|
      format.html { redirect_to offenders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offender
      @offender = Offender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offender_params
      params.require(:offender).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offenders_helper.rb
module OffendersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ATest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offenders/_form.html.erb
<%= form_for(@offender) do |f| %>
  <% if @offender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offender.errors.count, "error") %> prohibited this offender from being saved:</h2>

      <ul>
      <% @offender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offenders/edit.html.erb
<h1>Editing offender</h1>

<%= render 'form' %>

<%= link_to 'Show', @offender %> |
<%= link_to 'Back', offenders_path %>

app/views/offenders/index.html.erb
<h1>Listing offenders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offenders.each do |offender| %>
      <tr>
        <td><%= offender.name %></td>
        <td><%= offender.age %></td>
        <td><%= link_to 'Show', offender %></td>
        <td><%= link_to 'Edit', edit_offender_path(offender) %></td>
        <td><%= link_to 'Destroy', offender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offender', new_offender_path %>

app/views/offenders/new.html.erb
<h1>New offender</h1>

<%= render 'form' %>

<%= link_to 'Back', offenders_path %>

app/views/offenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @offender.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @offender.age %>
</p>

<%= link_to 'Edit', edit_offender_path(@offender) %> |
<%= link_to 'Back', offenders_path %>